import { Injectable } from '@nestjs/common';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import * as googleCredentials from '../google-credentials.json';

@Injectable()
export class AttendanceService {
  async initSheet() {
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: googleCredentials.client_email,
      key: googleCredentials.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    const doc = new GoogleSpreadsheet(
      '1V5SY55VS3JIfFkhHHKBWWQbO_aqU9Jc6FDWUq7b6xOg',
      serviceAccountAuth,
    );
    await doc.loadInfo();
    return doc;
  }

  async createData(data: any) {
    const doc = await this.initSheet();
    const sheet = doc.sheetsByTitle['學生報到機2021.8'];
    const result = await sheet.addRow(data, {
      insert: true,
    });

    return { rowNumber: result.rowNumber };
  }
}
