import {
  Body,
  Controller,
  Post,
  Req,
  UnauthorizedException,
  UseGuards,
} from '@nestjs/common';
import { AttendanceService } from './attendance.service';
import { AuthGuard } from 'src/auth/auth.guard';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import * as googleCredentials from '../google-credentials.json';

@Controller('attendance')
export class AttendanceController {
  constructor(private readonly service: AttendanceService) {}

  @UseGuards(AuthGuard)
  @Post('sendForm')
  async sendForm(@Body() body, @Req() req) {
    if (req.user.role !== 'admin') throw new UnauthorizedException();

    //日期	IP	卡/電話/名	出席堂數	狀態	功課份數	款項	在中心支付	無限Video	折扣	其他項目	其他項目總價
    const data = {
      日期: new Date().toLocaleString('en-US', { timeZone: 'Asia/Hong_Kong' }),
      IP: `${body.ipAddress}(${req.user.username})`,
      '卡/電話/名': !isNaN(body.studentName)
        ? body.studentName
        : parseInt(body.studentName),
      出席堂數: body.lessonCount,
      狀態: body.studentStatus === '出席' ? '' : body.studentStatus,
      功課份數: body.homework,
      款項: body.paymentAmount,
      在中心支付:
        body.paymentMethod === '無' ? '' : body.paymentMethod === '上門支付',
      無限Video: body.otherItems.includes('無限Video') ? 80 : '',
      折扣: body.discountAmount === 0 ? '' : body.discountAmount,
      其他項目: body.otherItems.join(','),
      其他項目總價: body.otherItemsPrice,
    };

    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: googleCredentials.client_email,
      key: googleCredentials.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });

    const doc = new GoogleSpreadsheet(
      '1V5SY55VS3JIfFkhHHKBWWQbO_aqU9Jc6FDWUq7b6xOg',
      serviceAccountAuth,
    );
    await doc.loadInfo();
    const sheet = doc.sheetsByTitle['學生報到機2021.8'];
    const maxRow = sheet.rowCount;
    await sheet.insertDimension('ROWS', {
      startIndex: maxRow,
      endIndex: maxRow + 1,
    });
    const rows = await sheet.getRows({
      offset: maxRow - 1,
      limit: 1,
    });
    rows[0].assign(data);
    await rows[0].save();

    return await maxRow;
  }
}
