version: '3.7'
services:
  frontend:
    container_name: frontend
    build: ./
    volumes:
        - /volume1/Dsessential_Web/qwik-app:/home/node/
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
 